"""65W-C: strictly coordinate-matched full FEM vs seven-region FE-NO fields.

Runs in regular Python on Windows server or personal M1 Max MacBook.
Input exports have headers instance,node_label,x,y,z,U1,U2,U3 (65W-B),
or X,Y,Z,U1,U2,U3 (older exports). FEM patches alone cover ONLY FE regions.

Commands:
 python scripts/65W_C_compare_fields.py --full FULL.csv --fe-left LEFT.csv \
    --fe-center CENTER.csv --fe-right RIGHT.csv --material-confirmed \
    --loading-confirmed --run-tag patch_audit

Add --no-ol CSV --no-l CSV --no-r CSV --no-or CSV to validate all seven.
Predictions must be actually generated by the trained NO; do NOT relabel
reference FEM nodes or reuse baseline-material CSV as middle-material data.
"""
import argparse
import csv
import json
import math
from pathlib import Path
from collections import defaultdict

import numpy as np

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT/'online_results_7region_65W_middle'/'C_field_comparison'
# Disjoint assignment, boundary nodes go to region on right except x=12.
REGIONS=[('NO_OL',-12.,-9.6),('FE_L',-9.6,-6.6),('NO_L',-6.6,-1.8),
         ('FE_C',-1.8,1.8),('NO_R',1.8,6.6),('FE_R',6.6,9.6),('NO_OR',9.6,12.)]
COMP=('U1','U2','U3')


def pick(d, name):
    for k,v in d.items():
        if k.strip().lower()==name.lower():return v
    raise ValueError('Missing column %s; present: %s'%(name,sorted(d)))


def load_points(path):
    points=[]
    with open(path,newline='') as f:
        for row in csv.DictReader(f):
            try:
                c=np.array([float(pick(row,k)) for k in ('x','y','z')],float)
                u=np.array([float(pick(row,k)) for k in COMP],float)
            except (TypeError,ValueError) as ex:
                # Non-specimen nodes may omit U; skip, never impute.
                continue
            if np.all(np.isfinite(c)) and np.all(np.isfinite(u)):
                points.append((c,u))
    if not points:raise RuntimeError('No finite xyz and U1/U2/U3 rows: '+str(path))
    return points


def zone(x):
    if x < -12.-1e-6 or x > 12.+1e-6:return None
    for i,(name,a,b) in enumerate(REGIONS):
        if a-1e-7 <= x < b-1e-7 or (i==len(REGIONS)-1 and a-1e-7<=x<=b+1e-7):
            return name
    return None


def grid_key(v,tol):
    return tuple(int(math.floor(float(k)/tol)) for k in v)


def index_ref(ref,tol):
    idx=defaultdict(list)
    for c,u in ref:idx[grid_key(c,tol)].append((c,u))
    return idx


def nearest(c,idx,tol):
    key=grid_key(c,tol)
    found=[]
    for dx in (-1,0,1):
        for dy in (-1,0,1):
            for dz in (-1,0,1):
                for rc,ru in idx.get((key[0]+dx,key[1]+dy,key[2]+dz),()):
                    dist=float(np.linalg.norm(rc-c))
                    if dist <= tol:found.append((dist,ru))
    if not found:return None
    found.sort(key=lambda v:v[0])
    if len(found)>1 and abs(found[0][0]-found[1][0]) < 1e-12:
        # Avoid selecting an ambiguous node from duplicate reference surfaces.
        return None
    return found[0][1]


def metric(a,b):
    a=np.asarray(a,float)
    b=np.asarray(b,float)
    if a.size==0:return None
    delta=b-a
    rmse=float(np.sqrt(np.mean(delta*delta)))
    norm=float(np.linalg.norm(a.ravel()))
    return {'rmse':rmse,'mae':float(np.mean(np.abs(delta))),
            'max_absolute_error':float(np.max(np.abs(delta))),
            'relative_l2_percent':float(100*np.linalg.norm(delta.ravel())/norm) if norm>1e-15 else None,
            'reference_rms':float(np.sqrt(np.mean(a*a)))}


def compare(args):
    target=OUT/args.run_tag
    if target.exists() and any(target.iterdir()):
        raise RuntimeError('Refusing to overwrite existing comparison: '+str(target))
    target.mkdir(parents=True,exist_ok=True)
    full=load_points(args.full)
    idx=index_ref(full,args.match_tol)
    sources={
        'NO_OL':args.no_ol,'FE_L':args.fe_left,'NO_L':args.no_l,
        'FE_C':args.fe_center,'NO_R':args.no_r,'FE_R':args.fe_right,'NO_OR':args.no_or
    }
    missing=[name for name,path in sources.items() if not path]
    by_region={};global_ref=[];global_hyb=[];pairs=[]
    for name,a,b in REGIONS:
        path=sources[name]
        ref_region=[(c,u) for c,u in full if zone(c[0])==name]
        entry={'source':path,'reference_nodes':len(ref_region),'is_neural_operator':name.startswith('NO_')}
        if path is None:
            entry.update(matched=0,coverage_pct=0.,status='MISSING_PREDICTION')
            by_region[name]=entry
            continue
        pred=[(c,u) for c,u in load_points(path) if zone(c[0])==name]
        matched_ref=[];matched_hyb=[];used=set()
        # Unique matching against all reference nodes (not extrapolated).
        for c,u in pred:
            ru=nearest(c,idx,args.match_tol)
            if ru is None:continue
            key=grid_key(c,args.match_tol/4.)
            if key in used:continue
            used.add(key)
            matched_ref.append(ru);matched_hyb.append(u)
            pairs.append([name]+list(c)+list(ru)+list(u))
        coverage=100*len(matched_ref)/max(1,len(ref_region))
        entry.update(matched=len(matched_ref),provided_nodes=len(pred),
                     coverage_pct=float(coverage),status='MATCHED' if matched_ref else 'NO_MATCH')
        if matched_ref:
            refarr=np.asarray(matched_ref); hybarr=np.asarray(matched_hyb)
            entry['U_vector']=metric(refarr,hybarr)
            for k in range(3):entry['U%d'%(k+1)]=metric(refarr[:,k],hybarr[:,k])
            global_ref.extend(matched_ref);global_hyb.extend(matched_hyb)
        by_region[name]=entry
    all_seven=not missing
    all_covered=all(v['coverage_pct']>=args.minimum_coverage for v in by_region.values())
    full_claim=bool(all_seven and all_covered and args.material_confirmed and args.loading_confirmed)
    report={
      'material':'middle: E1=46500 E2=12500 G12=4750 MPa (user must independently confirm full FEM ODB material)',
      'match_tolerance_mm':args.match_tol,'minimum_coverage_per_region_pct':args.minimum_coverage,
      'matching_method':'exact coordinate proximity (NO spatial interpolation performed)',
      'full_fem_csv':str(Path(args.full).resolve()),
      'physical_same_material_declared':bool(args.material_confirmed),
      'same_load_and_boundary_conditions_declared':bool(args.loading_confirmed),
      'all_seven_prediction_sources_supplied':all_seven,
      'all_seven_regions_reach_coverage_requirement':all_covered,
      'full_hybrid_validation_claim_allowed':full_claim,
      'missing_neural_operator_or_patch_regions':missing,
      'per_region':by_region,
      'warning':'Patch FEM CSVs do not include trained NO field predictions. Metrics for supplied regions cannot be represented as whole-beam error when ANY region is missing.',
      'coordinate_warning':'If mesh nodes differ, near-zero matching may result; export onto common evaluation points or implement proper mesh interpolation. Do not inflate matching tolerance arbitrarily.',
    }
    if global_ref:
        a=np.asarray(global_ref); b=np.asarray(global_hyb)
        report['SAMPLED_POINT_METRICS_NOT_FULL_UNLESS_COVERED']={
            'U_vector':metric(a,b), **{'U%d'%(i+1):metric(a[:,i],b[:,i]) for i in range(3)}}
        report['matched_points']=int(len(a))
    with open(target/'65W_C_field_comparison.json','w') as f:json.dump(report,f,indent=2)
    with open(target/'65W_C_matched_nodes.csv','w',newline='') as f:
        w=csv.writer(f);w.writerow(['region','x','y','z','FEM_U1','FEM_U2','FEM_U3',
                                     'Hybrid_U1','Hybrid_U2','Hybrid_U3']);w.writerows(pairs)
    print('Matched:',len(pairs),'full reference rows:',len(full))
    print('Missing:',missing)
    print('FULL-HYBRID VALIDATION CLAIM:',full_claim)
    for k,v in by_region.items():print('%7s: %5d matched; %6.2f%% coverage'%(k,v['matched'],v['coverage_pct']))
    print('Saved:',target)
    if not pairs:raise SystemExit(2)
    if not full_claim:print('PARTIAL comparison only: never report this as full 7-region accuracy.')


def selftest():
    assert zone(-10)=='NO_OL' and zone(-8)=='FE_L' and zone(-4)=='NO_L'
    assert zone(0)=='FE_C' and zone(4)=='NO_R' and zone(8)=='FE_R' and zone(11)=='NO_OR'
    ref=[(np.array([0.,0.,0.]),np.array([1.,2.,3.]))]
    z=nearest(np.array([0.,0.,0.]),index_ref(ref,1e-4),1e-4)
    assert np.allclose(z,[1,2,3])
    m=metric([1.,2.],[1.,2.]);assert m['rmse']==0.0
    print('65W-C selftest PASS')


def main():
    p=argparse.ArgumentParser()
    p.add_argument('--stage',choices=['selftest','compare'],default='compare')
    p.add_argument('--full',help='Full FEM beam nodal export at SAME middle material')
    for opt in ['fe-left','fe-center','fe-right','no-ol','no-l','no-r','no-or']:
        p.add_argument('--'+opt,default=None)
    p.add_argument('--run-tag',default='patches_only')
    p.add_argument('--match-tol',type=float,default=1e-4)
    p.add_argument('--minimum-coverage',type=float,default=95.0)
    p.add_argument('--material-confirmed',action='store_true')
    p.add_argument('--loading-confirmed',action='store_true')
    a=p.parse_args()
    if a.stage=='selftest':selftest();return
    if not a.full: p.error('--full is required for comparison')
    if a.match_tol <= 0 or a.match_tol>0.05:p.error('--match-tol must be 0 < tol <= 0.05 mm')
    compare(a)

if __name__=='__main__':main()
